-- 정규식을 이용해서 코드를 더 깔끔하게 만들 수 있음 (잘 알아둘 것!)
/*  
	-- LIKE 연산자를 이용해서 작성한 코드 --
	SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
	FROM ANIMAL_INS AS I
	JOIN ANIMAL_OUTS AS O
	ON I.ANIMAL_ID = O.ANIMAL_ID
	WHERE I.SEX_UPON_INTAKE LIKE 'Intact%' 
	AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%'
		OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
	ORDER BY I.ANIMAL_ID
*/

SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I
JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE REGEXP 'Intact' 
AND O.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered'
ORDER BY I.ANIMAL_ID